// <auto-generated />
namespace Stations.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddScheduleItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddScheduleItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201304141857528_AddScheduleItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
